### ISSUE TITLE
"throw_away_the_lime" task can not be executed

### ISSUE THREAD

**Issue by AlexWanghaoming** [NVlabs/progprompt-vh#8]
I found that the example task "throw_away_the_lime" can not be executed successfully in virtualhome v. 2.2.4. I just followed the provided example:
> "throw_away_the_lime": "def throw_away_the_lime():\n\t# 0: walk to kitchen\n\twalk('kitchen')\n\t# 1: find garbage can\n\tfind('garbagecan')\n\t# 2: grab lime\n\tfind('lime')\n\tassert('close' to 'lime')\n\t\telse: find('lime')\n\tgrab('lime')\n\t# 3: put lime in garbage can\n\tfind('garbagecan')\n\tassert('close' to 'garbagecan' )  \n\t\telse: find('garbagecan')\n\tassert('garbagecan' is 'closed' )\n\t\telse: close('garbagecan')\n\topen('garbagecan')\n\tassert('lime' in 'hands' )\n\t\telse: find('lime')\n\t\telse: grab('lime')\n\tassert('close' to 'garbagecan' )  \n\t\telse: find('garbagecan')\n\tassert('garbagecan' is 'opened' )\n\t\telse: open('garbagecan')\n\tputin('lime', 'garbagecan')\n\tassert('close' to 'garbagecan' )\n\t\telse: find('garbagecan')\n\tassert('garbagecan' is 'opened' )\n\t\telse: open('garbagecan')\n\tclose('garbagecan')\n\t# 4: Done",

and got an error at step "find(lime)":

> {'0': {'message': 'ScriptExcutor 0: PROCESS WALK: Can not select object: lime. REASON: No interaction positions\nEXECUTION_GENERAL: Script is impossible to execute\n\n'}}

**Comment by zzxrepository** [comment]
`<char0> [walk] <kitchen> (205)
-----------------
<char0> [find] <garbagecan> (229)
current_obj：
<garbagecan> (229)
state:
<virtualhome.simulation.evolving_graph.environment.EnvironmentState object at 0x0000020D9F72FFD0>
char_node: <character> (1)
Traceback (most recent call last):
  File "E:\Agent\text\progprompt-vh\scripts\run_eval.py", line 309, in <module>
    planner_executer(args=args)
  File "E:\Agent\text\progprompt-vh\scripts\run_eval.py", line 236, in planner_executer
    final_states, initial_states, exec_per_task = run_execution(args,
  File "E:\Agent\text\progprompt-vh\scripts\utils_execute.py", line 306, in run_execution
    success, final_state, _ = executor.execute(Script([script]))
  File "E:\Agent\text\progprompt-vh\virtualhome\virtualhome\simulation\evolving_graph\execution.py", line 1448, in execute
    state = next(self.call_action_method(future_script, state, info, self.char_index), None)
  File "E:\Agent\text\progprompt-vh\virtualhome\virtualhome\simulation\evolving_graph\execution.py", line 1460, in call_action_method
    return executor.execute(script, state, info, char_index, modify, in_place)
  File "E:\Agent\text\progprompt-vh\virtualhome\virtualhome\simulation\evolving_graph\execution.py", line 230, in execute
    return _walk_find_executor.execute(script, state, info, char_index, modify, in_place)
TypeError: execute() takes 5 positional arguments but 7 were given
CLOSING PROC`

@AlexWanghaoming  I also meet the similar problems,when find objects ,Do you solvw the problem?  Can you share with me？

**Comment by Cloudthink1** [comment]
> ## ` [walk] (205)
> [find] (229) current_obj： (229) state: <virtualhome.simulation.evolving_graph.environment.EnvironmentState object at 0x0000020D9F72FFD0> char_node: (1) Traceback (most recent call last): File "E:\Agent\text\progprompt-vh\scripts\run_eval.py", line 309, in planner_executer(args=args) File "E:\Agent\text\progprompt-vh\scripts\run_eval.py", line 236, in planner_executer final_states, initial_states, exec_per_task = run_execution(args, File "E:\Agent\text\progprompt-vh\scripts\utils_execute.py", line 306, in run_execution success, final_state, _ = executor.execute(Script([script])) File "E:\Agent\text\progprompt-vh\virtualhome\virtualhome\simulation\evolving_graph\execution.py", line 1448, in execute state = next(self.call_action_method(future_script, state, info, self.char_index), None) File "E:\Agent\text\progprompt-vh\virtualhome\virtualhome\simulation\evolving_graph\execution.py", line 1460, in call_action_method return executor.execute(script, state, info, char_index, modify, in_place) File "E:\Agent\text\progprompt-vh\virtualhome\virtualhome\simulation\evolving_graph\execution.py", line 230, in execute return _walk_find_executor.execute(script, state, info, char_index, modify, in_place) TypeError: execute() takes 5 positional arguments but 7 were given CLOSING PROC`
> 
> [@AlexWanghaoming](https://github.com/AlexWanghaoming) I also meet the similar problems,when find objects ,Do you solvw the problem? Can you share with me？

 I also meet the similar problems,when find objects ,Do you solvw the problem? Can you share with me？
